"use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from 'next/image';
import "./globals.css";
import MiniKitProvider from "@/components/minikit-provider";
import dynamic from "next/dynamic";
import NextAuthProvider from "@/components/next-auth-provider";
import { Network, Tokens } from "@worldcoin/minikit-js";
import { FaHome, FaInfoCircle, FaHeadset } from "react-icons/fa";
import carga from '@/public/images/carga_buenocambios.jpg';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BuenoCambios",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const ErudaProvider = dynamic(
    () => import("../components/Eruda/").then((c) => c.ErudaProvider),
    {
      ssr: false,
    }
  );

  return (
    <html lang="es">
      <body className={inter.className}>
        {/* Encabezado con título y menú */}
        <header>
          <h1 className="title">BuenoCambios</h1>
        </header>

        {/* Imagen de carga */}
        <div className="flex justify-center mt-4">
          <Image 
            src={carga} 
            alt="Carga BuenoCambios" 
            className="carga_bc" 
            width={800} 
            height={600} 
          />
        </div>

        {/* Footer fijo */}
        <footer className="footer">
          <a href="/informacion" className="footer-item">
            <FaInfoCircle />
            <span>Información</span>
          </a>
          <a href="/" className="footer-item">
            <FaHome />
            <span>Inicio</span>
          </a>
          <a href="/soporte" className="footer-item">
            <FaHeadset />
            <span>Soporte</span>
          </a>
        </footer>

        {/* Proveedores de autenticación y MiniKit */}
        <NextAuthProvider>
          <ErudaProvider>
            <MiniKitProvider>
              {children}
            </MiniKitProvider>
          </ErudaProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}

// Representa los tokens con los que el usuario puede pagar y la cantidad de cada uno
export type TokensPayload = {
  symbol: Tokens;
  token_amount: string;
};

export type PayCommandInput = {
  reference: string;
  to: string;
  tokens: TokensPayload[];
  network?: Network; // Opcional
  description: string;
};

